// Generated by CoffeeScript 1.9.0
(function() {
  module.exports = {
    exprNotEqual: function(value, escapeColumn) {
      if (value === null) {
        return escapeColumn + ' IS NOT NULL';
      } else {
        return escapeColumn + ' IS NULL OR ' + escapeColumn + ' <> ' + this.escape(value);
      }
    },
    exprEqual: function(value, escapeColumn) {
      if (value === null) {
        return escapeColumn + ' IS NULL';
      } else {
        return escapeColumn + ' = ' + this.escape(value);
      }
    }
  };

}).call(this);
