// Generated by CoffeeScript 1.9.2
(function() {
  var AbstractClient, PSqlServerClient,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  AbstractClient = require('../AbstractClient');

  PSqlServerClient = (function(superClass) {
    extend(PSqlServerClient, superClass);

    function PSqlServerClient() {
      return PSqlServerClient.__super__.constructor.apply(this, arguments);
    }

    PSqlServerClient.prototype.begin = notImplemented;

    PSqlServerClient.prototype.commit = notImplemented;

    PSqlServerClient.prototype.rollback = notImplemented;

    PSqlServerClient.prototype.query = notImplemented;

    PSqlServerClient.prototype.end = notImplemented;

    return PSqlServerClient;

  })(AbstractClient);

  module.exports = {
    createConnection: function(options, callback) {}
  };

}).call(this);
