// Generated by CoffeeScript 1.9.0
(function() {
  var AbstractClient, OracleClient,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  AbstractClient = require('../AbstractClient');

  OracleClient = (function(_super) {
    __extends(OracleClient, _super);

    function OracleClient() {
      return OracleClient.__super__.constructor.apply(this, arguments);
    }

    OracleClient.prototype.begin = notImplemented;

    OracleClient.prototype.commit = notImplemented;

    OracleClient.prototype.rollback = notImplemented;

    OracleClient.prototype.query = notImplemented;

    OracleClient.prototype.end = notImplemented;

    return OracleClient;

  })(AbstractClient);

  module.exports = {
    createConnection: function(options, callback) {}
  };

}).call(this);
