// Generated by CoffeeScript 1.9.3
var factory;

factory = function(require) {
  return {
    isNumeric: function(obj) {
      return !Array.isArray(obj) && (obj - parseFloat(obj) + 1) >= 0;
    },
    isObject: function(obj) {
      return typeof obj === 'object' && obj !== null;
    },
    notEmptyString: function(str) {
      return typeof str === 'string' && str.length > 0;
    }
  };
};

module.exports = factory(require);
