// Generated by CoffeeScript 1.10.0
var log4js;

if (!global.log4js) {
  log4js = global.log4js = require('log4js');
  log4js.configure({
    "appenders": [
      {
        "type": "console",
        "layout": {
          "type": "colored"
        }
      }
    ],
    "levels": {
      "[all]": "INFO"
    }
  });
}

module.exports = global.log4js;
