// Generated by CoffeeScript 1.10.0
var PlaceHolderParser;

module.exports = PlaceHolderParser = (function() {
  function PlaceHolderParser(beginStr, endStr) {
    var endWithWordChar, reg, special;
    if (beginStr == null) {
      beginStr = '__';
    }
    if ('string' !== typeof beginStr || beginStr.length === 0) {
      throw new Error('Invalid begin string');
    }
    if (arguments.length < 2) {
      endStr = beginStr;
    } else if (arguments.length > 2) {
      throw new Error('More than 2 arguments has been given');
    } else if ('string' !== typeof endStr || endStr.length === 0) {
      throw new Error('Invalid end string');
    }
    special = /([\\^$.|?*+()\[\]{}])/g;
    beginStr = beginStr.replace(special, '\\$1');
    endStr = endStr.replace(special, '\\$1');
    reg = ['(?:(["\'`])|'];
    if (/^\\?\w/.test(beginStr.substring(0, 2))) {
      reg.push('\\b');
    }
    reg.push(beginStr);
    reg.push('((?:(?!', endStr);
    if (endWithWordChar = /\w/.test(endStr[endStr.length - 1])) {
      reg.push('\\b');
    }
    reg.push(').)+)(', endStr, ')?');
    if (endWithWordChar) {
      reg.push('\\b');
    }
    reg.push(')');
    this.reg = new RegExp(reg.join(''), 'g');
  }

  PlaceHolderParser.prototype.parse = function(str) {
    var cursor, indexes, list, quoting;
    list = [];
    indexes = {};
    cursor = 0;
    quoting = false;
    str.replace(this.reg, function(match, quote, key, end, start, str) {
      if (quoting) {
        if (quote === quoting) {
          quoting = false;
        }
      } else {
        if (quote) {
          quoting = quote;
        } else if (end) {
          if (cursor < start) {
            list[list.length] = str.substring(cursor, start);
          }
          cursor = start + match.length;
          indexes[key] || (indexes[key] = []);
          indexes[key].push(list.length);
          list[list.length] = match;
        }
      }
      return match;
    });
    if (cursor < str.length) {
      list[list.length] = str.substring(cursor, str.length);
    }
    return [list, indexes];
  };

  PlaceHolderParser.prototype.replace = function(str, callback) {
    var quoting;
    quoting = false;
    return str.replace(this.reg, function(match, quote, key, end, start, str) {
      if (quoting) {
        if (quote === quoting) {
          quoting = false;
        }
      } else {
        if (quote) {
          quoting = quote;
        } else if (end) {
          match = callback(key);
        }
      }
      return match;
    });
  };

  PlaceHolderParser.prototype.precompile = function(str) {
    var except, i, index, indexes, j, key, len, len1, list, ref, ref1;
    ref = this.parse(str), list = ref[0], indexes = ref[1];
    except = [];
    for (key in indexes) {
      ref1 = indexes[key];
      for (i = 0, len = ref1.length; i < len; i++) {
        index = ref1[i];
        except.push(index);
        list[index] = "' + (context['" + key + "'] || '') + '";
      }
    }
    for (index = j = 0, len1 = list.length; j < len1; index = ++j) {
      str = list[index];
      if (-1 === except.indexOf(index)) {
        list[index] = str.replace(/'/g, "\\'");
      }
    }
    return "function template(context) {\n    if (context === null || 'object' !== typeof context) {\n        context = {};\n    }\n    return '" + (list.join('')) + "';\n}";
  };

  PlaceHolderParser.prototype.unsafeCompile = function(str) {
    var fn;
    fn = "" + (this.precompile(str));
    eval(fn);
    return template;
  };

  PlaceHolderParser.prototype.safeCompile = function(str) {
    var indexes, list, ref;
    ref = this.parse(str), list = ref[0], indexes = ref[1];
    return function(context) {
      var _list, i, index, key, len, ref1;
      if (context === null || 'object' !== typeof context) {
        return list.join('');
      }
      _list = list.slice();
      for (key in indexes) {
        if (context.hasOwnProperty(key)) {
          ref1 = indexes[key];
          for (i = 0, len = ref1.length; i < len; i++) {
            index = ref1[i];
            _list[index] = context[key];
          }
        }
      }
      return _list.join('');
    };
  };

  return PlaceHolderParser;

})();
