// Generated by CoffeeScript 1.12.4
var ColumnCompiler, SchemaCompiler, Sqlite3SchemaCompiler, _, tools,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

_ = require('lodash');

tools = require('../../tools');

SchemaCompiler = require('../../schema/SchemaCompiler');

ColumnCompiler = require('./ColumnCompiler');

module.exports = Sqlite3SchemaCompiler = (function(superClass) {
  extend(Sqlite3SchemaCompiler, superClass);

  function Sqlite3SchemaCompiler() {
    return Sqlite3SchemaCompiler.__super__.constructor.apply(this, arguments);
  }

  Sqlite3SchemaCompiler.prototype.ColumnCompiler = ColumnCompiler;

  Sqlite3SchemaCompiler.prototype.validUpdateActions = ['no_action', 'restrict', 'cascade', 'set_null', 'set_default'];

  return Sqlite3SchemaCompiler;

})(SchemaCompiler);
